# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
# ! REMEMBER ABOUT POLISH LETTERS !
# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !

config-version = 2

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

after-startup-command = [
  # requires FelixKratz JankyBorders
  'exec-and-forget borders active_color=0xf5e1fee4 inactive_color=0xff494d64 width=5.0'
]

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

persistent-workspaces = ["W", "E", "R", "S", "D", "F"]

accordion-padding = 30
[gaps]
  inner.horizontal = 8
  inner.vertical =   8
  outer.left =       8
  outer.bottom =     8
  outer.top =        4
  outer.right =      8

# Define my fancy unicorn key notation
[key-mapping.key-notation-to-key-code]
  up___ = 'i'
  down_ = 'k'
  left_ = 'j'
  right = 'l'

[mode.main.binding]

  ctrl-left_ = 'focus --boundaries-action wrap-around-the-workspace left'
  ctrl-down_ = 'focus --boundaries-action wrap-around-the-workspace down'
  ctrl-up___ = 'focus --boundaries-action wrap-around-the-workspace up'
  ctrl-right = 'focus --boundaries-action wrap-around-the-workspace right'

  ctrl-alt-left_ = 'move left'
  ctrl-alt-down_ = 'move down'
  ctrl-alt-up___ = 'move up'
  ctrl-alt-right = 'move right'

  ctrl-shift-left_ = 'join-with left'
  ctrl-shift-down_ = 'join-with down'
  ctrl-shift-up___ = 'join-with up'
  ctrl-shift-right = 'join-with right'

  ctrl-u = 'layout accordion horizontal vertical'
  ctrl-o = 'layout tiles horizontal vertical'
  ctrl-alt-space = 'layout floating tiling'

  ctrl-p = 'fullscreen'

  # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
  # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
  # alt-a = 'focus parent'

  ctrl-w = 'workspace W'
  ctrl-e = 'workspace E'
  ctrl-r = 'workspace R'
  ctrl-s = 'workspace S'
  ctrl-d = 'workspace D'
  ctrl-f = 'workspace F'

  ctrl-alt-w = 'move-node-to-workspace W'
  ctrl-alt-e = 'move-node-to-workspace E'
  ctrl-alt-r = 'move-node-to-workspace R'
  ctrl-alt-s = 'move-node-to-workspace S'
  ctrl-alt-d = 'move-node-to-workspace D'
  ctrl-alt-f = 'move-node-to-workspace F'

  # disable hide application or other macOS shortcuts
  cmd-h = []
  cmd-alt-h = []

  ctrl-alt-c = 'reload-config'

  ctrl-alt-x = 'mode resize'

[mode.resize.binding]
  ctrl-left_ = 'resize width -50'
  ctrl-down_ = 'resize height +50'
  ctrl-up___ = 'resize height -50'
  ctrl-right = 'resize width +50'
  enter = 'mode main'
  esc = 'mode main'
