# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
# ! REMEMBER ABOUT POLISH LETTERS !
# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
config-version = 2
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

persistent-workspaces = ["🍷", "🍸", "🍹", "🦀", "🦋", "🪶"]
[workspace-to-monitor-force-assignment]
  '🍷' = 'main'
  '🍸' = 'main'
  '🍹' = 'main'
  '🦀' = ['secondary', 'main']
  '🦋' = ['secondary', 'main']
  '🪶' = ['secondary', 'main']

accordion-padding = 30
[gaps]
  inner.horizontal = 8
  inner.vertical =   8
  outer.left =       8
  outer.bottom =     8
  outer.top =        [{ monitor."built-in.*" = 2 }, 8]
  outer.right =      8

##################################################

[mode.main.binding]
  ctrl-j = 'focus --boundaries all-monitors-outer-frame left'
  ctrl-k = 'focus --boundaries all-monitors-outer-frame down'
  ctrl-i = 'focus --boundaries all-monitors-outer-frame up'
  ctrl-l = 'focus --boundaries all-monitors-outer-frame right'

  ctrl-alt-j = 'move left'
  ctrl-alt-k = 'move down'
  ctrl-alt-i = 'move up'
  ctrl-alt-l = 'move right'

  ctrl-shift-j = 'join-with left'
  ctrl-shift-k = 'join-with down'
  ctrl-shift-i = 'join-with up'
  ctrl-shift-l = 'join-with right'

  ctrl-u         = 'layout horizontal vertical'
  ctrl-o         = 'layout tiles accordion'
  ctrl-alt-space = 'layout floating tiling'

  ctrl-p = 'macos-native-fullscreen'

  ctrl-w = "workspace 🍷"
  ctrl-e = "workspace 🍸"
  ctrl-r = "workspace 🍹"
  ctrl-s = "workspace 🦀"
  ctrl-d = "workspace 🦋"
  ctrl-f = "workspace 🪶"

  ctrl-alt-w = "move-node-to-workspace 🍷"
  ctrl-alt-e = "move-node-to-workspace 🍸"
  ctrl-alt-r = "move-node-to-workspace 🍹"
  ctrl-alt-s = "move-node-to-workspace 🦀"
  ctrl-alt-d = "move-node-to-workspace 🦋"
  ctrl-alt-f = "move-node-to-workspace 🪶"

  # disable hide application or other macOS shortcuts
  cmd-h = []
  cmd-alt-h = []

  ctrl-alt-c = 'reload-config'

  ctrl-alt-z = 'mode chocofi'
  ctrl-alt-x = 'mode resize-main'

##################################################

[mode.chocofi.binding]
  ctrl-alt-cmd-a = 'focus left'
  ctrl-alt-cmd-e = 'focus up'
  ctrl-alt-cmd-h = 'focus down'
  ctrl-alt-cmd-i = 'focus right'

  ctrl-alt-cmd-o = 'move left'
  ctrl-alt-cmd-y = 'move down'
  ctrl-alt-cmd-k = 'move up'
  ctrl-alt-cmd-j = 'move right'

  ctrl-alt-cmd-quote = 'join-with left'
  ctrl-alt-cmd-u     = 'join-with up'
  ctrl-alt-cmd-p     = 'join-with down'
  ctrl-alt-cmd-q     = 'join-with right'

  ctrl-alt-cmd-semicolon = 'layout horizontal vertical'
  ctrl-alt-cmd-period    = 'layout tiles accordion'
  ctrl-alt-cmd-comma     = 'layout floating tiling'

  ctrl-alt-cmd-f = 'macos-native-fullscreen'

  ctrl-alt-cmd-s = "workspace 🍷"
  ctrl-alt-cmd-n = "workspace 🍸"
  ctrl-alt-cmd-t = "workspace 🍹"
  ctrl-alt-cmd-w = "workspace 🦀"
  ctrl-alt-cmd-m = "workspace 🦋"
  ctrl-alt-cmd-d = "workspace 🪶"

  shift-ctrl-alt-cmd-s = "move-node-to-workspace 🍷"
  shift-ctrl-alt-cmd-n = "move-node-to-workspace 🍸"
  shift-ctrl-alt-cmd-t = "move-node-to-workspace 🍹"
  shift-ctrl-alt-cmd-w = "move-node-to-workspace 🦀"
  shift-ctrl-alt-cmd-m = "move-node-to-workspace 🦋"
  shift-ctrl-alt-cmd-d = "move-node-to-workspace 🪶"

  # disable hide application or other macOS shortcuts
  cmd-h = []
  cmd-alt-h = []

  ctrl-alt-c = 'reload-config'

  ctrl-alt-z = 'mode main'
  ctrl-alt-x = 'mode resize-chocofi'

##################################################

[mode.resize-main.binding]
  ctrl-j = 'resize width -50'
  ctrl-k = 'resize height +50'
  ctrl-i = 'resize height -50'
  ctrl-l = 'resize width +50'
  enter = 'mode main'
  esc = 'mode main'

[mode.resize-chocofi.binding]
  ctrl-a = 'resize width -50'
  ctrl-e = 'resize height +50'
  ctrl-h = 'resize height -50'
  ctrl-i = 'resize width +50'
  enter = 'mode chocofi'
  esc = 'mode chocofi'

##################################################

[[on-window-detected]] # Preview
  if.app-id = 'com.apple.Preview'
  run = 'layout floating'

[[on-window-detected]] # AppCleaner
  if.app-id = 'net.freemacsoft.AppCleaner'
  run = 'layout floating'

[[on-window-detected]] # Passwords
  if.app-id = 'com.apple.Passwords'
  run = 'layout floating'
